/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bai_tap_lon_qldgd;

import java.awt.Color;
import java.awt.Font;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class HoadonJPanel extends javax.swing.JPanel {
    String chuoi = "";
    
    /**
     * Creates new form HoadonJPanel
     */
    public HoadonJPanel() {
        initComponents();
        table_Giohang.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_Giohang.getTableHeader().setOpaque(false);
        table_Giohang.getTableHeader().setForeground(new Color(0,153,204));
        table_Giohang.setRowHeight(25);
        
        table_dshoadon.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_dshoadon.getTableHeader().setOpaque(false);
        table_dshoadon.getTableHeader().setForeground(new Color(0,153,204));
        table_dshoadon.setRowHeight(25);
        
        table_dsmathang.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_dsmathang.getTableHeader().setOpaque(false);
        table_dsmathang.getTableHeader().setForeground(new Color(0,153,204));
        table_dsmathang.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_dsmathang = new javax.swing.JTable();
        btn_timkiemmathang = new javax.swing.JButton();
        jtx_timkiemmathang = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_Giohang = new javax.swing.JTable();
        btnCapnhatGioHang = new javax.swing.JButton();
        btnXoaGioHang = new javax.swing.JButton();
        jtx_editsoluong = new javax.swing.JTextField();
        btn_resettthd1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dshoadon = new javax.swing.JTable();
        btn_timkiemhoadon = new javax.swing.JButton();
        btnXoadshd = new javax.swing.JButton();
        jtx_timkiemhoadon = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        btnTongthanhtien = new javax.swing.JButton();
        btnLaphoadon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtx_mahoadon = new javax.swing.JTextField();
        jtx_tenkhachhang = new javax.swing.JTextField();
        jtx_sdt = new javax.swing.JTextField();
        jtx_ngaytao = new javax.swing.JTextField();
        jtx_diachi = new javax.swing.JTextField();
        jtx_tongthanhtien = new javax.swing.JTextField();
        jcombo_trangthai = new javax.swing.JComboBox<>();
        btn_resettthd = new javax.swing.JButton();
        btn_updatehd = new javax.swing.JButton();
        XUATHD = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(42, 189, 241));

        jLabel7.setFont(new java.awt.Font("#9Slide03 SVND Sari", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Danh sách hóa đơn");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1100, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Danh sách mặt hàng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 190, 40));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("Giỏ hàng");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 90, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Danh sách hoá đơn");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        table_dsmathang.setAutoCreateRowSorter(true);
        table_dsmathang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TBĐ01", "Công tắc 1 chiều lớn", "Thiết bị điện", "30", "Cái", "21000"},
                {"TBĐ02", "Công tắc 2 chiều lớn", "Thiết bị điện", "25", "Cái", "30000"},
                {"TBĐ03", "Ổ cắm lớn", "Thiết bị điện", "40", "Cái", "39500"},
                {"TBĐ04", "Ổ cắm 3 chấu", "Thiết bị điện", "32", "Cái", "4800"},
                {"TBĐ05", "CB 2 pha", "Thiết bị điện", "10", "Cái", "750000"},
                {"TBĐ06", "CB 4 pha", "Thiết bị điện", "15", "Cái", "1150000"},
                {"TBĐ07", "Tủ điện", "Thiết bị điện", "20", "Cái", "190000"},
                {"DC01", "Máy khoan pin", "Dụng cụ làm điện", "10", "Cái", "1200000"},
                {"DC02", "Máy khoan điện", "Dụng cụ làm điện", "15", "Cái", "1700000"},
                {"DC03", "Kiềm mỏ nhọn", "Dụng cụ làm điện", "17", "Cái", "66000"},
                {"DC04", "Kiềm cắt", "Dụng cụ làm điện", "12", "Cái", "52000"},
                {"LK01", "Vít tôn 2p", "Linh kiện - Phụ kiện", "20000", "100 gram", "2000"},
                {"LK02", "Vít tôn 3p", "Linh kiện - Phụ kiện", "30000", "100 gram", "2200"},
                {"LK03", "Vít tôn 5p", "Linh kiện - Phụ kiện", "40000", "100 gram", "2400"},
                {"LK04", "Bulong M6", "Linh kiện - Phụ kiện", "25000", "100 gram", "9000"},
                {"LK05", "Bulong M8", "Linh kiện - Phụ kiện", "35000", "100 gram", "10000"},
                {"LK06", "Dây 1.0", "Linh kiện - Phụ kiện", "10000", "mét", "4000"}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Loại", "Số lượng", "Đơn vị tính", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_dsmathang.setRowHeight(25);
        table_dsmathang.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_dsmathang.setShowHorizontalLines(true);
        table_dsmathang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dsmathangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_dsmathang);

        btn_timkiemmathang.setBackground(new java.awt.Color(51, 204, 255));
        btn_timkiemmathang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_timkiemmathang.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemmathang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btn_timkiemmathang.setText(" Tìm kiếm");
        btn_timkiemmathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemmathangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_timkiemmathang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtx_timkiemmathang))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_timkiemmathang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtx_timkiemmathang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 440, 230));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        jPanel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel15KeyPressed(evt);
            }
        });

        table_Giohang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table_Giohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Giohang.setRowHeight(25);
        table_Giohang.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_Giohang.setShowHorizontalLines(true);
        table_Giohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_giohangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_Giohang);

        btnCapnhatGioHang.setBackground(new java.awt.Color(51, 204, 255));
        btnCapnhatGioHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapnhatGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhatGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/change.png"))); // NOI18N
        btnCapnhatGioHang.setText("Cập nhật số lượng");
        btnCapnhatGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapnhatGioHangMouseClicked(evt);
            }
        });
        btnCapnhatGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatgiohangActionPerformed(evt);
            }
        });

        btnXoaGioHang.setBackground(new java.awt.Color(51, 204, 255));
        btnXoaGioHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete_1.png"))); // NOI18N
        btnXoaGioHang.setText("Xóa");
        btnXoaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaGioHanggActionPerformed(evt);
            }
        });

        jtx_editsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_editsoluongKeyPressed(evt);
            }
        });

        btn_resettthd1.setBackground(new java.awt.Color(51, 213, 255));
        btn_resettthd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/change.png"))); // NOI18N
        btn_resettthd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resettthd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnXoaGioHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapnhatGioHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtx_editsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_resettthd1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCapnhatGioHang)
                        .addComponent(btnXoaGioHang)
                        .addComponent(jtx_editsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_resettthd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 650, 290));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Thông tin hoá đơn");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        table_dshoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KH01", "Thưc", "0987654321", "P6, TPCL", "2023-06-13", "Đã thanh toán", "12000000"},
                {"KH02", "Phương", "0123456789", "P3, TPCL", "2023-06-13", "Chưa thanh toán", "3000000"}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Ngày tạo", "Trạng thái", "Tổng thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_dshoadon.setRowHeight(25);
        table_dshoadon.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_dshoadon.setShowHorizontalLines(true);
        table_dshoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dshoadonMouseClicked(evt);
            }
        });
        table_dshoadon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_dshoadonKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_dshoadon);

        btn_timkiemhoadon.setBackground(new java.awt.Color(51, 204, 255));
        btn_timkiemhoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_timkiemhoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btn_timkiemhoadon.setText(" Tìm kiếm");
        btn_timkiemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemhoadonActionPerformed(evt);
            }
        });

        btnXoadshd.setBackground(new java.awt.Color(51, 204, 255));
        btnXoadshd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoadshd.setForeground(new java.awt.Color(255, 255, 255));
        btnXoadshd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete_1.png"))); // NOI18N
        btnXoadshd.setText("Xóa");
        btnXoadshd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoadshdActionPerformed(evt);
            }
        });

        jtx_timkiemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_timkiemhoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_timkiemhoadon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtx_timkiemhoadon)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoadshd)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoadshd)
                    .addComponent(btn_timkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtx_timkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 670, 230));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        jPanel14.setForeground(new java.awt.Color(0, 153, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTongthanhtien.setBackground(new java.awt.Color(51, 204, 255));
        btnTongthanhtien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTongthanhtien.setForeground(new java.awt.Color(255, 255, 255));
        btnTongthanhtien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gross.png"))); // NOI18N
        btnTongthanhtien.setText("Tổng thành tiền");
        btnTongthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongthanhtienActionPerformed(evt);
            }
        });
        jPanel14.add(btnTongthanhtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        btnLaphoadon.setBackground(new java.awt.Color(51, 204, 255));
        btnLaphoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLaphoadon.setForeground(new java.awt.Color(255, 255, 255));
        btnLaphoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-file_1.png"))); // NOI18N
        btnLaphoadon.setText("Lập hoá đơn");
        btnLaphoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaphoadonActionPerformed(evt);
            }
        });
        jPanel14.add(btnLaphoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Mã HĐ");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Tên KH");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("SĐT");
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Địa chỉ");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 53, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Ngày tạo: ");
        jPanel14.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 95, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Trạng thái");
        jPanel14.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 137, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Tổng thành tiền");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 177, -1, -1));

        jtx_mahoadon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_mahoadonKeyPressed(evt);
            }
        });
        jPanel14.add(jtx_mahoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 53, 121, -1));

        jtx_tenkhachhang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_tenkhachhangKeyPressed(evt);
            }
        });
        jPanel14.add(jtx_tenkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 95, 121, -1));

        jtx_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_sdtKeyPressed(evt);
            }
        });
        jPanel14.add(jtx_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 137, 121, -1));

        jtx_ngaytao.setEditable(false);
        jPanel14.add(jtx_ngaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 97, 126, -1));
        jPanel14.add(jtx_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 55, 126, -1));

        jtx_tongthanhtien.setEditable(false);
        jPanel14.add(jtx_tongthanhtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 179, 174, -1));

        jcombo_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đã thanh toán" }));
        jcombo_trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo_trangthaiActionPerformed(evt);
            }
        });
        jPanel14.add(jcombo_trangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 137, 126, -1));

        btn_resettthd.setBackground(new java.awt.Color(51, 213, 255));
        btn_resettthd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/change.png"))); // NOI18N
        btn_resettthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resettthdActionPerformed(evt);
            }
        });
        jPanel14.add(btn_resettthd, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 11, 47, 30));

        btn_updatehd.setBackground(new java.awt.Color(51, 204, 255));
        btn_updatehd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_updatehd.setForeground(new java.awt.Color(255, 255, 255));
        btn_updatehd.setText("Cập nhật HD");
        btn_updatehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatehdActionPerformed(evt);
            }
        });
        jPanel14.add(btn_updatehd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        XUATHD.setBackground(new java.awt.Color(51, 204, 255));
        XUATHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        XUATHD.setForeground(new java.awt.Color(255, 255, 255));
        XUATHD.setText("XUẤT HĐ");
        XUATHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XUATHDActionPerformed(evt);
            }
        });
        jPanel14.add(XUATHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 90, 30));

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 470, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaphoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaphoadonActionPerformed
        // TODO add your handling code here:
        if(jtx_mahoadon.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hoá đơn !");
            jtx_mahoadon.requestFocus();
        }else if(jtx_tenkhachhang.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khách hàng !");
            jtx_tenkhachhang.requestFocus();
        }else if(jtx_sdt.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại !");
            jtx_sdt.requestFocus();
        }else if(jtx_sdt.getText().toString().length()!=10){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại la 10 số !");
            jtx_sdt.requestFocus();
        }else if(jtx_diachi.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ !");
            jtx_diachi.requestFocus();
        }else if(chuoi==""){
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn hoá đơn này chưa thanh toán ?");
            if(chon==JOptionPane.YES_OPTION){
                chuoi="Chưa thanh toán";
                jtx_tongthanhtien.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái hoá đơn");
                jtx_ngaytao.requestFocus();
            }
            
        }else if(jtx_tongthanhtien.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhấn nút Tổng thành tiền");
            jtx_ngaytao.requestFocus();
        }else if(Integer.parseInt(jtx_tongthanhtien.getText())==0){
            JOptionPane.showMessageDialog(this, "Giỏ hàng rỗng, vui lòng thêm mặt hàng vào giỏ hàng để lập hoá đơn !");
            jtx_ngaytao.requestFocus();
        }else{
              DefaultTableModel tmodel = (DefaultTableModel) table_dshoadon.getModel();
              int i,found =0;
              for(i=0;i<table_dshoadon.getRowCount();i++){
                  if(tmodel.getValueAt(i, 0).toString().equals(jtx_mahoadon.getText())==true){
                      found=1;
                      break;
                  }
              }
              if(found==0){
                  String data[]={jtx_mahoadon.getText(),jtx_tenkhachhang.getText(), jtx_sdt.getText(),jtx_diachi.getText(),jtx_ngaytao.getText(),chuoi,jtx_tongthanhtien.getText()};
                  tmodel.addRow(data);
                  JOptionPane.showMessageDialog(this, "Lập hoá đơn thành công !");
                  jtx_mahoadon.setText("");
                  jtx_tenkhachhang.setText("");
                  jtx_sdt.setText("");
                  jtx_diachi.setText("");
                  jtx_ngaytao.setText("");
                  jcombo_trangthai.setSelectedIndex(0);
                  chuoi="";
                  jtx_tongthanhtien.setText("");
                  jtx_mahoadon.requestFocus();
                  DefaultTableModel ghmodel = (DefaultTableModel) table_Giohang.getModel();
                  ghmodel.setRowCount(0);
              }else{
                  JOptionPane.showMessageDialog(this, "Mã hoá đơn đã tồn tại, vui lòng nhập lại mã hoá đơn !");
                  jtx_mahoadon.requestFocus();
              }
              
              
        }
    }//GEN-LAST:event_btnLaphoadonActionPerformed

    private void btnTongthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongthanhtienActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_Giohang.getModel();
        if(table_Giohang.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Giỏ hàng rỗng, vui lòng thêm mặt hàng vào giỏ hàng để lập hoá đơn !");
            return;
        }else{
           int i;
        long s=0,giatri;
        for(i=0;i<table_Giohang.getRowCount();i++){
            giatri = Long.parseLong(tmodel.getValueAt(i, 4).toString());
            s+=giatri;
        }
        String tongthanhtien = String.format("%d", s);
        jtx_tongthanhtien.setText(tongthanhtien);
        jtx_ngaytao.setText(java.time.LocalDate.now().toString());
        }
        
    }//GEN-LAST:event_btnTongthanhtienActionPerformed

    private void jtx_timkiemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_timkiemhoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_timkiemhoadonActionPerformed

    private void btnXoadshdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoadshdActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tblmodel = (DefaultTableModel) table_dshoadon.getModel() ;
        
        if(table_dshoadon.getSelectedRowCount()==1){
            tblmodel.removeRow(table_dshoadon.getSelectedRow());
            jtx_mahoadon.setText("");
                  jtx_tenkhachhang.setText("");
                  jtx_sdt.setText("");
                  jtx_diachi.setText("");
                  jtx_ngaytao.setText("");
                  jcombo_trangthai.setSelectedIndex(0);
                  chuoi="";
                  jtx_tongthanhtien.setText("");
                  jtx_mahoadon.requestFocus();
        }else{
            if(table_dshoadon.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Danh sách rỗng !");
            }else{
                JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng cần xoá !");
            }
        }
    }//GEN-LAST:event_btnXoadshdActionPerformed

    private void btn_timkiemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemhoadonActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) table_dshoadon.getModel();
        String searchValue = jtx_timkiemhoadon.getText();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table_dshoadon.setRowSorter(sorter);
        RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter(searchValue, 0);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_btn_timkiemhoadonActionPerformed

    private void btn_timkiemmathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemmathangActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_dsmathang.getModel();
        String searchValue = jtx_timkiemmathang.getText();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table_dsmathang.setRowSorter(sorter);
        RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter(searchValue, 0);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_btn_timkiemmathangActionPerformed

    private void table_dsmathangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dsmathangMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) table_dsmathang.getModel();
         DefaultTableModel tmodel = (DefaultTableModel) table_Giohang.getModel();
         int choice = JOptionPane.showConfirmDialog(this, "Bạn chọn mặt hàng này ?");
         if(choice == JOptionPane.YES_OPTION){
             String mahang = model.getValueAt(table_dsmathang.getSelectedRow(), 0).toString();
             String tenhang = model.getValueAt(table_dsmathang.getSelectedRow(),1).toString();
             String dongia = model.getValueAt(table_dsmathang.getSelectedRow(), 5).toString();
             int chon = JOptionPane.showConfirmDialog(this, "Bạn chọn số lượng là 1 ?");
             String soluong="1";
             if(chon==JOptionPane.NO_OPTION){
                soluong = JOptionPane.showInputDialog("Nhập số lượng ");
                for(int i=0;i<soluong.length();i++){
                    if(Character.isLetter(soluong.charAt(i))){
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số !");
                        return ;
                    }
                }
                if(Long.parseLong(soluong)<1){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng > 0");
                    return;
                }
             }  
             long dongia1 = Long.parseLong(dongia);
             long soluong1 = Long.parseLong(soluong);
             long thanhtien1 = soluong1*dongia1;
             long soluong2;
             
             
                       
             long soluong4 = Long.parseLong(model.getValueAt(table_dsmathang.getSelectedRow(), 3).toString());
            if(soluong1 >soluong4){
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng nhỏ hơn trong danh sách mặt hàng");
                        
            }else{
                String thanhtien = String.format("%d",thanhtien1);
                String data[]= {mahang,tenhang,soluong,dongia,thanhtien};
                tmodel.addRow(data);  
                for(int i=0;i<table_dsmathang.getRowCount();i++){
                 if(model.getValueAt(i, 0).toString().equals(mahang)){
                     soluong2 = Long.parseLong(model.getValueAt(i, 3).toString()) ;
                     soluong2 -= soluong1;
                     String soluongx =  String.format("%d", soluong2);
                     model.setValueAt(soluongx, i, 3);
                 }
             }
             long soluong3;
             for(int i=0;i<table_dsmathang.getRowCount();i++){
                  soluong3 = Long.parseLong(model.getValueAt(i, 3).toString());
                 if(soluong3<1){
                     model.removeRow(i);
                 }
             }
            }
             
         }
    }//GEN-LAST:event_table_dsmathangMouseClicked

    private void btnXoaGioHanggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaGioHanggActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_Giohang.getModel();
        if(table_Giohang.getSelectedRowCount()==1){
            tmodel.removeRow(table_Giohang.getSelectedRow());
        }else{
            if(table_Giohang.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Giỏ hàng rỗng");
            }else{
                JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng cần xoá !");
            }
        }
    }//GEN-LAST:event_btnXoaGioHanggActionPerformed

    private void btnCapnhatgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatgiohangActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_Giohang.getModel();
        DefaultTableModel model = (DefaultTableModel) table_dsmathang.getModel();

            if(jtx_editsoluong.getText().isEmpty()==true){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng");
                jtx_editsoluong.requestFocus();
            }else{
                 String soluong  = jtx_editsoluong.getText(); 
                if(Long.parseLong(soluong)<1){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng > 0");
                    jtx_editsoluong.requestFocus();
                }else{
                    
                    
                String dongia = tmodel.getValueAt(table_Giohang.getSelectedRow(), 3).toString();  

                long dongia1 = Long.parseLong(dongia);
                long soluong1 = Long.parseLong(soluong);
                long thanhtien1 = soluong1*dongia1;
                long soluong2;
                
                String mahang = tmodel.getValueAt(table_Giohang.getSelectedRow(), 0).toString();
                long soluong4;
                String thanhtien = String.format("%d",thanhtien1);
                for(int i=0;i<table_dsmathang.getRowCount();i++){
                    if(model.getValueAt(i, 0).toString().equals(mahang)){
                        soluong4 = Long.parseLong(model.getValueAt(i, 3).toString());
                        if(soluong1-1>soluong4){
                            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng nhỏ hơn trong danh sách mặt hàng");
                            jtx_editsoluong.requestFocus();
                            return;
                        }

                    }
                }
                
                for(int i=0;i<table_dsmathang.getRowCount();i++){
                    if(model.getValueAt(i, 0).toString().equals(mahang)){
                        soluong2 = Long.parseLong(model.getValueAt(i, 3).toString()) ;
                        soluong2 -= soluong1;
                        String soluongx =  String.format("%d", soluong2);
                        model.setValueAt(soluongx, i, 3);
                    }
                }
                long soluong3;
                for(int i=0;i<table_dsmathang.getRowCount();i++){
                     soluong3 = Long.parseLong(model.getValueAt(i, 3).toString());
                    if(soluong3<1){
                        model.removeRow(i);
                    }
                }
                
                
             ;
                tmodel.setValueAt(soluong, table_Giohang.getSelectedRow(), 2);
                tmodel.setValueAt(thanhtien, table_Giohang.getSelectedRow(), 4);
                
                JOptionPane.showMessageDialog(this, "Cập nhật thành công !");
                jtx_editsoluong.setText("");
                

                
            }
            
        }           
            
    }//GEN-LAST:event_btnCapnhatgiohangActionPerformed

    private void table_giohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_giohangMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_Giohang.getModel();
        String soluong = tmodel.getValueAt(table_Giohang.getSelectedRow(), 2).toString();
        
        jtx_editsoluong.setText(soluong);
    }//GEN-LAST:event_table_giohangMouseClicked

    private void btnCapnhatGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapnhatGioHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapnhatGioHangMouseClicked

    private void jcombo_trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo_trangthaiActionPerformed
        // TODO add your handling code here:
        chuoi=jcombo_trangthai.getItemAt(jcombo_trangthai.getSelectedIndex());
    }//GEN-LAST:event_jcombo_trangthaiActionPerformed

    private void jtx_mahoadonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_mahoadonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_mahoadonKeyPressed

    private void jtx_tenkhachhangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_tenkhachhangKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            jtx_tenkhachhang.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chữ !");
        }else{
            jtx_tenkhachhang.setEditable(true);
        }
        jtx_tenkhachhang.setEditable(true);
    }//GEN-LAST:event_jtx_tenkhachhangKeyPressed

    private void jtx_sdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_sdtKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jtx_sdt.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập SĐT là số !!!");
        }else{
            jtx_sdt.setEditable(true);
        }
        jtx_sdt.setEditable(true);
    }//GEN-LAST:event_jtx_sdtKeyPressed

    private void btn_resettthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resettthdActionPerformed
        // TODO add your handling code here:
        jcombo_trangthai.setSelectedIndex(0);
        jtx_mahoadon.setText("");
        jtx_tenkhachhang.setText("");
        jtx_sdt.setText("");
        jtx_diachi.setText("");
        jtx_ngaytao.setText("");
        jtx_tongthanhtien.setText("");
        jtx_mahoadon.requestFocus();
    }//GEN-LAST:event_btn_resettthdActionPerformed

    private void btn_resettthd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resettthd1ActionPerformed
        // TODO add your handling code here:
        int i;
        DefaultTableModel ghmodel = (DefaultTableModel) table_Giohang.getModel();
        ghmodel.setRowCount(0);
    }//GEN-LAST:event_btn_resettthd1ActionPerformed

    private void btn_updatehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatehdActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_dshoadon.getModel();
        if(table_dshoadon.getSelectedRowCount()==1){
            if(jtx_tenkhachhang.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khách hàng !");
            jtx_tenkhachhang.requestFocus();
        }else if(jtx_sdt.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại !");
            jtx_sdt.requestFocus();
        }else if(jtx_diachi.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ !");
            jtx_diachi.requestFocus();
        }else{
            String tenkh = jtx_tenkhachhang.getText();
            String sdt = jtx_sdt.getText();
            String diachi = jtx_diachi.getText();
            String trangthai = jcombo_trangthai.getItemAt(jcombo_trangthai.getSelectedIndex());

            tmodel.setValueAt(tenkh, table_dshoadon.getSelectedRow(), 1);
            tmodel.setValueAt(sdt, table_dshoadon.getSelectedRow(), 2);
            tmodel.setValueAt(diachi, table_dshoadon.getSelectedRow(), 3);
            tmodel.setValueAt(trangthai, table_dshoadon.getSelectedRow(), 5);
            jtx_mahoadon.setText("");
            jtx_tenkhachhang.setText("");
            jtx_sdt.setText("");
            jtx_diachi.setText("");
            jtx_ngaytao.setText("");
            jcombo_trangthai.setSelectedIndex(0);
            chuoi="";
            jtx_tongthanhtien.setText("");
            jtx_mahoadon.requestFocus();
            JOptionPane.showMessageDialog(this, "Cập nhật hoá đơn thành công");
        }
       
        }
    }//GEN-LAST:event_btn_updatehdActionPerformed

    private void table_dshoadonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_dshoadonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_dshoadonKeyPressed

    private void table_dshoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dshoadonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel) table_dshoadon.getModel();
        String mahd = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 0).toString();
        String tenkh = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 1).toString();
        String sdt = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 2).toString();
        String diachi = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 3).toString();
        String trangthai = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 5).toString();
        String tongtien = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 6).toString();
        String ngaytao = tmodel.getValueAt(table_dshoadon.getSelectedRow(), 4).toString();
        
        jtx_mahoadon.setText(mahd);
        jtx_mahoadon.setEditable(false);
        jtx_ngaytao.setText(ngaytao);
        jtx_ngaytao.setEditable(false);
        jtx_tongthanhtien.setText(tongtien);
        jtx_tongthanhtien.setEditable(false);
        jtx_tenkhachhang.setText(tenkh);
        jtx_sdt.setText(sdt);
        jtx_diachi.setText(diachi);
        jcombo_trangthai.setSelectedItem(trangthai);
    }//GEN-LAST:event_table_dshoadonMouseClicked

    private void jPanel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel15KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel15KeyPressed

    private void jtx_editsoluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_editsoluongKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jtx_editsoluong.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số !");
        }else{
             jtx_editsoluong.setEditable(true);
        }
        jtx_editsoluong.setEditable(true);
    }//GEN-LAST:event_jtx_editsoluongKeyPressed

    private void XUATHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XUATHDActionPerformed
        // TODO add your handling code here:
        
        if(jtx_mahoadon.getText().isEmpty()==false){
        try{
            String mahd = jtx_mahoadon.getText();
            String tenkh = jtx_tenkhachhang.getText();
            String sdt = jtx_sdt.getText();
            String diachi = jtx_diachi.getText();
            String trangthai = jcombo_trangthai.getItemAt(jcombo_trangthai.getSelectedIndex());
            String ngaytao = jtx_ngaytao.getText();
            String tongthanhtien = jtx_tongthanhtien.getText();
            FileWriter fw = new FileWriter("hoadon_"+mahd+".txt");
            
               fw.write("Ma hoa don: "+mahd+"\n"+
                    "Ten khach hang: "+tenkh + "\n"+
                    "So dien thoai: "+sdt+"\n"+
                    "Dia chi: "+diachi+"\n"+
                    "Ngay tao: "+ngaytao+"\n"+
                    "Trang thai: "+trangthai+"\n"+
                     "Tong thanh tien: "+tongthanhtien);
                      fw.close(); 

           
            
        }catch (Exception e){
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(this, "Xuất file thành công");
        }else{
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn để xuất file");
        }
    }//GEN-LAST:event_XUATHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XUATHD;
    private javax.swing.JButton btnCapnhatGioHang;
    private javax.swing.JButton btnLaphoadon;
    private javax.swing.JButton btnTongthanhtien;
    private javax.swing.JButton btnXoaGioHang;
    private javax.swing.JButton btnXoadshd;
    private javax.swing.JButton btn_resettthd;
    private javax.swing.JButton btn_resettthd1;
    private javax.swing.JButton btn_timkiemhoadon;
    private javax.swing.JButton btn_timkiemmathang;
    private javax.swing.JButton btn_updatehd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jcombo_trangthai;
    private javax.swing.JTextField jtx_diachi;
    private javax.swing.JTextField jtx_editsoluong;
    private javax.swing.JTextField jtx_mahoadon;
    private javax.swing.JTextField jtx_ngaytao;
    private javax.swing.JTextField jtx_sdt;
    private javax.swing.JTextField jtx_tenkhachhang;
    private javax.swing.JTextField jtx_timkiemhoadon;
    private javax.swing.JTextField jtx_timkiemmathang;
    private javax.swing.JTextField jtx_tongthanhtien;
    private javax.swing.JTable table_Giohang;
    private javax.swing.JTable table_dshoadon;
    private javax.swing.JTable table_dsmathang;
    // End of variables declaration//GEN-END:variables
}
