/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bai_tap_lon_qldgd;

import java.awt.Color;
import java.awt.Font;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class ThongkeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongkeJPanel
     */
    public ThongkeJPanel() {
        initComponents();
        table_dshoadon.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_dshoadon.getTableHeader().setOpaque(false);
        table_dshoadon.getTableHeader().setForeground(new Color(0,153,204));
        table_dshoadon.setRowHeight(25);
        
        table_dshoadonctt.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_dshoadonctt.getTableHeader().setOpaque(false);
        table_dshoadonctt.getTableHeader().setForeground(new Color(0,153,204));
        table_dshoadonctt.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dshoadon = new javax.swing.JTable();
        jtxt_doanhthu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxt_tongtienhddtt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_dshoadonctt = new javax.swing.JTable();
        jtxt_tongtienhdctt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_timkiemhoadon = new javax.swing.JButton();
        jtx_timkiemhoadon = new javax.swing.JTextField();
        btn_Thongke = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Danh sách hoá đơn chưa thanh toán");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 320, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Danh sách hoá đơn ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_dshoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12", "Hưng", "0326204844", "P4, TPCL", "14-6-2023", "Đã thanh toán", "120000"},
                {"34", "Phương", "0917172737", "P3 TPCL", "12-6-2023", "Chưa thanh toán", "13000"},
                {"56", "Thức", "0943521928", "P2, TPCL", "11-6-2023", "Đã thanh toán", "1700000"},
                {"78", "Khương", "0912345671", "P6, TPCL", "12-6-2023", "Chưa thanh toán", "12000000"}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Ngày tạo", "Trạng thái", "Tổng thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_dshoadon.setRowHeight(25);
        table_dshoadon.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_dshoadon.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_dshoadon.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table_dshoadon);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 34, 919, 130));
        jPanel4.add(jtxt_doanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 182, 390, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("Tổng doanh thu : ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 182, -1, -1));
        jPanel4.add(jtxt_tongtienhddtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 232, 390, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setText("Tổng tiền đã thanh toán: ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 232, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 990, 290));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        table_dshoadonctt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Ngày tạo", "Trạng thái", "Tổng thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_dshoadonctt.setRowHeight(25);
        table_dshoadonctt.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_dshoadonctt.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_dshoadonctt.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(table_dshoadonctt);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Tổng số tiền chưa thanh toán: ");

        btn_timkiemhoadon.setBackground(new java.awt.Color(51, 204, 255));
        btn_timkiemhoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_timkiemhoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btn_timkiemhoadon.setText(" Tìm kiếm");
        btn_timkiemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemhoadonActionPerformed(evt);
            }
        });

        jtx_timkiemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_timkiemhoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_tongtienhdctt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_timkiemhoadon)
                .addGap(18, 18, 18)
                .addComponent(jtx_timkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_timkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtx_timkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_tongtienhdctt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 990, 270));

        btn_Thongke.setBackground(new java.awt.Color(0, 204, 255));
        btn_Thongke.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_Thongke.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thongke.setText("Thống kê");
        btn_Thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongkeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 262, 47));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("VUI LÒNG NHẤN NÚT THỐNG KÊ ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timkiemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemhoadonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_dshoadonctt.getModel();
        String searchValue = jtx_timkiemhoadon.getText();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table_dshoadonctt.setRowSorter(sorter);
        RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter(searchValue, 0);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_btn_timkiemhoadonActionPerformed

    private void jtx_timkiemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_timkiemhoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_timkiemhoadonActionPerformed

    private void btn_ThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongkeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_dshoadon.getModel();
        DefaultTableModel tmodel = (DefaultTableModel) table_dshoadonctt.getModel();
        if(table_dshoadonctt.getRowCount()==0){
          int i;
        String trangthai ="";
        long tongdoanhthu =0, tonghddtt = 0, tonghdctt=0,tongthanhtien;
        for(i=0;i<table_dshoadon.getRowCount();i++){
            trangthai = model.getValueAt(i, 5).toString();
            tongthanhtien = Long.parseLong(model.getValueAt(i, 6).toString());
            if(trangthai.equals("Đã thanh toán")==true){
                tonghddtt+=tongthanhtien;
            }else{
                tonghdctt+=tongthanhtien;
            }
            tongdoanhthu+=tongthanhtien;
        }
        String doanhthu = String.format("%d", tongdoanhthu);
        String tienhddtt = String.format("%d", tonghddtt);
        String tienhdctt = String.format("%d", tonghdctt);
        jtxt_doanhthu.setText(doanhthu);
        jtxt_tongtienhdctt.setText(tienhdctt);
        jtxt_tongtienhddtt.setText(tienhddtt);

        for(i=0;i<table_dshoadon.getRowCount();i++){
            trangthai = model.getValueAt(i, 5).toString();
            String mahd= model.getValueAt(i, 0).toString();
            String tenkh = model.getValueAt(i, 1).toString();
            String sdt = model.getValueAt(i, 2).toString();
            String diachi = model.getValueAt(i, 3).toString();
            String ngaytao = model.getValueAt(i, 4).toString();
            String tongthanhtien1 =  model.getValueAt(i, 6).toString();
            if(trangthai.equals("Đã thanh toán")==false ){
                String data[] = {mahd,tenkh,sdt,diachi,ngaytao,trangthai,tongthanhtien1};
                tmodel.addRow(data);
            }
        }  
        }
        

    }//GEN-LAST:event_btn_ThongkeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Thongke;
    private javax.swing.JButton btn_timkiemhoadon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtx_timkiemhoadon;
    private javax.swing.JTextField jtxt_doanhthu;
    private javax.swing.JTextField jtxt_tongtienhdctt;
    private javax.swing.JTextField jtxt_tongtienhddtt;
    private javax.swing.JTable table_dshoadon;
    private javax.swing.JTable table_dshoadonctt;
    // End of variables declaration//GEN-END:variables
}
