/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bai_tap_lon_qldgd;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class TrangchuJPanel extends javax.swing.JPanel {
    String chuoi="";
    public JTable getTable_mathang() {
        return table_mathang;
    }

    public TrangchuJPanel(JTable table_mathang) {
        this.table_mathang = table_mathang;
    }

    public void setTable_mathang(JTable table_mathang) {
        this.table_mathang = table_mathang;
    }

    /**
     * Creates new form TrangchuJPanel
     */
    public TrangchuJPanel() {
        initComponents();
        table_mathang.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        table_mathang.getTableHeader().setOpaque(false);
        table_mathang.getTableHeader().setForeground(new Color(0,153,204));
        table_mathang.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mathang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxmahang = new javax.swing.JTextField();
        jtxtenhang = new javax.swing.JTextField();
        jcbloai = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxsoluong = new javax.swing.JTextField();
        jtxdvtinh = new javax.swing.JTextField();
        jtxdongia = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        jtx_timkiem = new javax.swing.JTextField();
        btn_sort = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(102, 204, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-file.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        table_mathang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_mathang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TBĐ01", "Công tắc 1 chiều lớn", "Thiết bị điện", "30", "Cái ", "21000"},
                {"TBĐ02", "Công tắc 2 chiều lớn", "Thiết bị điện", "25", "Cái", "30000"},
                {"TBĐ03", "Ổ cắm lớn", "Thiết bị điện", "40", "Cái", "39500"},
                {"TBĐ04", "Ổ cắm 3 chấu", "Thiết bị điện", "32", "Cái ", "48000"},
                {"TBĐ05", "CB 2 pha", "Thiết bị điện", "10", "Cái ", "750000"},
                {"TBĐ06", "CB 4 pha", "Thiết bị điện", "15", "Cái", "1150000"},
                {"TBĐ07", "Tủ điện", "Thiết bị điện", "20", "Cái ", "190000"},
                {"DC01", "Máy khoan pin", "Dụng cụ làm điện", "10", "Cái", "1200000"},
                {"DC02", "Máy khoan điện", "Dụng cụ làm điện", "15", "Cái", "1700000"},
                {"DC03", "Kiềm mỏ nhọn", "Dụng cụ làm điện", "17", "Cái ", "66000"},
                {"DC04", "Kiềm cắt", "Dụng cụ làm điện", "12", "Cái", "52000"},
                {"LK01", "Vít tôn 2p", "Linh kiện - Phụ kiện", "20000", "100 gram", "2000"},
                {"LK02", "Vít tôn 3p", "Linh kiện - Phụ kiện", "30000", "100 gram", "2200"},
                {"LK03", "Vít tôn 5p", "Linh kiện - Phụ kiện", "40000", "100 gram", "2400"},
                {"LK04", "Bulong M6", "Linh kiện - Phụ kiện", "25000", "100 gram", "9000"},
                {"LK05", "Bulong M8", "Linh kiện - Phụ kiện", "35000", "100 gram", "10000"},
                {"LK06", "Dây 1.0", "Linh kiện - Phụ kiện", "10000", "mét", "4000"}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Loại", "Số lượng", "Đơn vị tính", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_mathang.setRowHeight(25);
        table_mathang.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table_mathang.setShowHorizontalLines(true);
        table_mathang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mathangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mathang);

        jPanel3.setBackground(new java.awt.Color(42, 189, 241));

        jLabel1.setFont(new java.awt.Font("#9Slide03 SVND Sari", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách mặt hàng");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(42, 189, 241));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã hàng :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tên hàng :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loại :");

        jtxmahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxmahangActionPerformed(evt);
            }
        });

        jtxtenhang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtenhangKeyPressed(evt);
            }
        });

        jcbloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết bị điện", "Dụng cụ làm điện", "Linh kiện - Phụ kiện", " " }));
        jcbloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbloaiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số lượng :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đơn vị tính :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Đơn giá :");

        jtxsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxsoluongKeyPressed(evt);
            }
        });

        jtxdvtinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxdvtinhActionPerformed(evt);
            }
        });

        jtxdongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxdongiaActionPerformed(evt);
            }
        });
        jtxdongia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxdongiaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtenhang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxmahang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbloai, 0, 237, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxdvtinh)
                    .addComponent(jtxdongia)
                    .addComponent(jtxsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxmahang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbloai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtxsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxdvtinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        btnEdit.setBackground(new java.awt.Color(102, 204, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 204, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 204, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btn_timkiem.setBackground(new java.awt.Color(51, 204, 255));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btn_timkiem.setText(" Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jtx_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btn_sort.setBackground(new java.awt.Color(102, 204, 255));
        btn_sort.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_sort.setForeground(new java.awt.Color(255, 255, 255));
        btn_sort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sort.png"))); // NOI18N
        btn_sort.setText("Sắp xếp");
        btn_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtx_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtx_timkiem))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnReset)
                    .addComponent(btn_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxmahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxmahangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxmahangActionPerformed

    private void jcbloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbloaiActionPerformed
        // TODO add your handling code here:
        chuoi = jcbloai.getItemAt(jcbloai.getSelectedIndex());
    }//GEN-LAST:event_jcbloaiActionPerformed

    private void jtxdvtinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxdvtinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxdvtinhActionPerformed

    private void jtxdongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxdongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxdongiaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(jtxmahang.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào mã hàng !");
            jtxmahang.requestFocus();
        }else if(jtxtenhang.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào tên hàng");
            jtxtenhang.requestFocus();
        }else if(jtxsoluong.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào số lượng !");
            jtxsoluong.requestFocus();
        }else if(Long.parseLong(jtxsoluong.getText())<1){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng > 0 !");
            jtxsoluong.requestFocus();
        }else if(jtxdvtinh.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn vị tính !");
            jtxdvtinh.requestFocus();
        }else if(jtxdongia.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn giá !");
            jtxdongia.requestFocus();
        }else if(Long.parseLong(jtxdongia.getText())<1){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn giá > 0 !");
            jtxdongia.requestFocus();
        }else{
            if(chuoi==""){
                chuoi="Thiết bị điện";
            }
            int i,found=0;
            DefaultTableModel tblmodel = (DefaultTableModel) table_mathang.getModel() ;
            for(i=0;i<table_mathang.getRowCount();i++){
                if(tblmodel.getValueAt(i, 0).toString().equals(jtxmahang.getText())==true){
                    found=1;
                    break;
                }
            }
            if(found==0){
                String data[] = {
                    jtxmahang.getText(),jtxtenhang.getText(),chuoi,jtxsoluong.getText(),jtxdvtinh.getText(),jtxdongia.getText()
                };
                tblmodel.addRow(data);
                JOptionPane.showMessageDialog(this, "Thêm vào danh sách thành công !");
                jtxmahang.setText("");
                jtxtenhang.setText("");
                jcbloai.setSelectedIndex(0);
                chuoi="";
                jtxsoluong.setText("");
                jtxdongia.setText("");
                jtxdvtinh.setText("");
                jtxmahang.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Mã hàng đã tồn tại trong danh sách, vui lòng nhập lại !!!");
                jtxmahang.requestFocus();
            }
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel) table_mathang.getModel() ;
        if(table_mathang.getSelectedRowCount()==1){
            if(jtxtenhang.getText().isEmpty()==true){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập vào tên hàng");
               jtxtenhang.requestFocus();
           }else if(jtxsoluong.getText().isEmpty()==true){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập vào số lượng !");
               jtxsoluong.requestFocus();
           }else if(Long.parseLong(jtxsoluong.getText())<0){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng >= 0 !");
               jtxsoluong.requestFocus();
           }else if(jtxdvtinh.getText().isEmpty()==true){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn vị tính !");
               jtxdvtinh.requestFocus();
           }else if(jtxdongia.getText().isEmpty()==true){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn giá !");
               jtxdongia.requestFocus();
           }else if(Long.parseLong(jtxdongia.getText())<1){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập vào đơn giá > 0 !");
               jtxdongia.requestFocus();
           }else{
               
               String mahang = tblmodel.getValueAt(table_mathang.getSelectedRow(), 0).toString();
               String tenhang = jtxtenhang.getText();
               String loai = chuoi;
               String soluong = jtxsoluong.getText();
               String dvtinh = jtxdvtinh.getText();
               String dongia = jtxdongia.getText();
               tblmodel.setValueAt(tenhang, table_mathang.getSelectedRow(), 1);
               tblmodel.setValueAt(loai, table_mathang.getSelectedRow(), 2);
               tblmodel.setValueAt(soluong, table_mathang.getSelectedRow(), 3);
               tblmodel.setValueAt(dvtinh, table_mathang.getSelectedRow(), 4);
               tblmodel.setValueAt(dongia, table_mathang.getSelectedRow(), 5);
               JOptionPane.showMessageDialog(this, "Đã sửa thành công mặt hàng có mã  '"+mahang+"'");
               jtxmahang.setText("");
                jtxtenhang.setText("");
                jcbloai.setSelectedIndex(0);
                chuoi="";
                jtxsoluong.setText("");
                jtxdongia.setText("");
                jtxdvtinh.setText("");
                jtxmahang.requestFocus();
               
           }
        }else{
            JOptionPane.showMessageDialog(this, "Chỉ được phép sửa mỗi lần 1 thông tin mặt h");
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tblmodel = (DefaultTableModel) table_mathang.getModel() ;
        
        if(table_mathang.getSelectedRowCount()==1){
            tblmodel.removeRow(table_mathang.getSelectedRow());
        }else{
            if(table_mathang.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Danh sách rỗng");
            }else{
                JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng cần xoá !!!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        jtxmahang.setText("");
        jtxtenhang.setText("");
        jcbloai.setSelectedItem("Thiết bị điện");
        jtxsoluong.setText("");
        jtxdvtinh.setText("");
        jtxdongia.setText("");
        jtxmahang.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void table_mathangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mathangMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel) table_mathang.getModel() ;
        String mahang = tblmodel.getValueAt(table_mathang.getSelectedRow(), 0).toString();
        String tenhang = tblmodel.getValueAt(table_mathang.getSelectedRow(),1).toString();
        String loai = tblmodel.getValueAt(table_mathang.getSelectedRow(),2).toString();
        String soluong = tblmodel.getValueAt(table_mathang.getSelectedRow(),3).toString();   
        String donvitinh = tblmodel.getValueAt(table_mathang.getSelectedRow(),4).toString();
        String dongia = tblmodel.getValueAt(table_mathang.getSelectedRow(),5).toString();
        
        jtxmahang.setText(mahang);
        jtxmahang.setEditable(false);
        jtxtenhang.setText(tenhang);
        jcbloai.setSelectedItem(loai);
        jtxsoluong.setText(soluong);
        jtxdvtinh.setText(donvitinh);
        jtxdongia.setText(dongia);
        
        

    }//GEN-LAST:event_table_mathangMouseClicked

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_mathang.getModel();
        String searchValue = jtx_timkiem.getText();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table_mathang.setRowSorter(sorter);
        RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter(searchValue, 0);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void jtxsoluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxsoluongKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jtxsoluong.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số !");
        }else{
             jtxsoluong.setEditable(true);
        }
        jtxsoluong.setEditable(true);
    }//GEN-LAST:event_jtxsoluongKeyPressed

    private void jtxdongiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxdongiaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jtxdongia.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đơn giá là số !");
        }else{
             jtxdongia.setEditable(true);
        }
        jtxdongia.setEditable(true);
    }//GEN-LAST:event_jtxdongiaKeyPressed

    private void jtxtenhangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtenhangKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtenhangKeyPressed

    private void btn_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_mathang.getModel();
        for(int i=0;i<model.getRowCount()-1;i++){
            for(int j=i+1;j<model.getRowCount();j++){
                String c1 = model.getValueAt(i, 1).toString();
                String c2 = model.getValueAt(j, 1).toString();
                if(c1.compareTo(c2)>0){
                    // lay thong tin 2 dong
                    String mahang1 = model.getValueAt(i, 0).toString();
                    String mahang2 = model.getValueAt(j, 0).toString();
                    String tenhang1 =model.getValueAt(i, 1).toString();
                    String tenhang2 =model.getValueAt(j, 1).toString();
                    String loai1 = model.getValueAt(i, 2).toString();
                    String loai2 = model.getValueAt(j, 2).toString();
                    String soluong1 = model.getValueAt(i, 3).toString();
                    String soluong2 = model.getValueAt(j, 3).toString();
                    String dvtinh1 = model.getValueAt(i, 4).toString();
                    String dvtinh2 = model.getValueAt(j, 4).toString();
                    String dongia1 = model.getValueAt(i, 5).toString();
                    String dongia2 = model.getValueAt(j, 5).toString();
                    // sua thong tin 2 dong voi nhau
                    model.setValueAt(mahang1, j, 0);
                    model.setValueAt(mahang2, i, 0);
                    model.setValueAt(tenhang1, j, 1);
                    model.setValueAt(tenhang2, i, 1);
                    model.setValueAt(loai1, j, 2);
                    model.setValueAt(loai2, i, 2);
                    model.setValueAt(soluong1, j, 3);
                    model.setValueAt(soluong2, i, 3);
                    model.setValueAt(dvtinh1, j, 4);
                    model.setValueAt(dvtinh2, i, 4);
                    model.setValueAt(dongia1, j, 5);
                    model.setValueAt(dongia2, i, 5);
                }
                
            }
        }
    }//GEN-LAST:event_btn_sortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btn_sort;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbloai;
    private javax.swing.JTextField jtx_timkiem;
    private javax.swing.JTextField jtxdongia;
    private javax.swing.JTextField jtxdvtinh;
    private javax.swing.JTextField jtxmahang;
    private javax.swing.JTextField jtxsoluong;
    private javax.swing.JTextField jtxtenhang;
    private javax.swing.JTable table_mathang;
    // End of variables declaration//GEN-END:variables
}
